package com.openbravo.pos.sales;

import com.openbravo.data.gui.ComboBoxValModel;
import java.awt.Component;
import java.util.List;

public class JProductAttListItem extends javax.swing.JPanel implements JProductAttEditI {

    private String attid;
    private ComboBoxValModel model;

    public JProductAttListItem(String attid, String label, String value, List<String> values) {

        this.attid = attid;

        initComponents();

        jLabel1.setText(label);

        for (String item : values) {
            jValues.addItem(item);
        }
        jValues.setSelectedItem(value);
    }

    public void assignSelection() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jValues.requestFocus();
            }
        });
    }

    public String getAttribute() {
        return attid;
    }

    public String getValue() {
        return (String) jValues.getSelectedItem();
    }

    public Component getComponent() {
        return this;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jValues = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("jLabel1");

        jValues.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                      .addContainerGap()
                      .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addComponent(jValues, javax.swing.GroupLayout.PREFERRED_SIZE, 193,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                      .addContainerGap(12, Short.MAX_VALUE)
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                              javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jValues, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                              javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox jValues;
    // End of variables declaration//GEN-END:variables

}
