-- Database upgrade script for DERBY
-- v3.70 - v3.80

--
-- UPDATE existing tables
--

ALTER TABLE PRODUCTS ADD COLUMN STOCKUNITS DOUBLE PRECISION DEFAULT 0;

-- UPDATE App' version
UPDATE APPLICATIONS SET NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = $APP_ID{};

-- final script
DELETE FROM SHAREDTICKETS;
