-- Database upgrade script for DERBY
-- v3.56 - v3.60

--
-- UPDATE existing tables
--

--
-- ALTER existing tables
--
ALTER TABLE CSVIMPORT ADD COLUMN CATEGORY VARCHAR(256) DEFAULT NULL;

ALTER TABLE CUSTOMERS ADD COLUMN TMPCOLUMN DOUBLE PRECISION DEFAULT 0;
UPDATE CUSTOMERS SET TMPCOLUMN=CURDEBT;
ALTER TABLE CUSTOMERS DROP COLUMN CURDEBT;
RENAME COLUMN CUSTOMERS.TMPCOLUMN TO CURDEBT;

UPDATE CUSTOMERS SET CURDEBT = NULL WHERE CURDEBT = 0;
--
-- ADD new tables
--
CREATE TABLE LINEREMOVED (
  REMOVEDDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NAME VARCHAR(256) DEFAULT NULL,
  TICKETID VARCHAR(256) DEFAULT NULL,
  PRODUCTID VARCHAR(256) DEFAULT NULL,
  PRODUCTNAME VARCHAR(256) DEFAULT NULL,
  UNITS DOUBLE PRECISION NOT NULL
);

-- UPDATE App' version
UPDATE APPLICATIONS SET NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = $APP_ID{};

-- final script
DELETE FROM SHAREDTICKETS;
