-- Database updater
-- JDL

-- Add column to products table
ALTER TABLE PRODUCTS ADD COLUMN WARRANTY BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE SHAREDTICKETS ADD COLUMN PICKUPID INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE STOCKDIARY ADD COLUMN AppUser VARCHAR(255);

CREATE SEQUENCE PICKUP_NUMBER START WITH 1;

UPDATE APPJL SET NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = $APP_ID{};
