-- Database upgrade script for HSQLDB
-- v3.56 - v3.60

--
-- UPDATE existing tables
--

--
-- ALTER existing tables
--
ALTER TABLE CSVIMPORT ADD COLUMN CATEGORY VARCHAR(255) DEFAULT NULL;

UPDATE CUSTOMERS SET CURDEBT = NULL WHERE CURDEBT = 0;
ALTER TABLE CUSTOMERS SET CURDEBT DOUBLE DEFAULT 0;
--
-- ADD new tables
--

CREATE TABLE LINEREMOVED (
  REMOVEDDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NAME VARCHAR(255) DEFAULT NULL,
  TICKETID VARCHAR(255) DEFAULT NULL,
  PRODUCTID VARCHAR(255) DEFAULT NULL,
  PRODUCTNAME VARCHAR(255) DEFAULT NULL,
  UNITS VARCHAR(255) DEFAULT NULL
);

-- UPDATE App' version
UPDATE APPLICATIONS SET NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = $APP_ID{};

-- final script
DELETE FROM SHAREDTICKETS;
