-- Database upgrade script for MySQL
-- v3.70 - v3.80

--
-- UPDATE existing tables
--
ALTER TABLE PRODUCTS ADD COLUMN STOCKUNITS DOUBLE DEFAULT 0 NOT NULL;

-- UPDATE App' version
UPDATE APPLICATIONS SET NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = $APP_ID{};

-- final script
DELETE FROM SHAREDTICKETS;
