-- Database upgrade script for MySQL
-- v3.56 - v3.60

--
-- UPDATE existing tables
--

--
-- ALTER existing tables
--
ALTER TABLE CSVIMPORT ADD COLUMN CATEGORY VARCHAR(255) DEFAULT NULL;

UPDATE CUSTOMERS SET CURDEBT = NULL WHERE CURDEBT = 0;
ALTER TABLE CUSTOMERS MODIFY CURDEBT DOUBLE DEFAULT 0 NOT NULL;
--
-- ADD new tables
--
CREATE TABLE LINEREMOVED (
  REMOVEDDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NAME varchar(255) DEFAULT NULL,
  TICKETID varchar(255) DEFAULT NULL,
  PRODUCTID varchar(255) DEFAULT NULL,
  PRODUCTNAME varchar(255) DEFAULT NULL,
  UNITS DOUBLE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- UPDATE App' version
UPDATE APPLICATIONS SET NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = $APP_ID{};

-- final script
DELETE FROM SHAREDTICKETS;
