-- Database upgrade script for MySQL
-- v3.55 - v3.56

--
-- UPDATE existing tables
--

--
-- ALTER existing tables
--
DROP TABLE TICKETSNUM_PAYMENT;
CREATE TABLE TICKETSNUM_PAYMENT (
    ID INTEGER not null AUTO_INCREMENT,
PRIMARY KEY(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO TICKETSNUM_PAYMENT VALUES (DEFAULT);

-- UPDATE App' version
UPDATE APPLICATIONS SET NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = $APP_ID{};

-- final script
DELETE FROM SHAREDTICKETS;
