-- Database upgrade script for PostgreSQL
-- v3.56 - v3.60

--
-- UPDATE existing tables
--

--
-- ALTER existing tables
--
ALTER TABLE CSVIMPORT ADD COLUMN CATEGORY VARCHAR DEFAULT NULL;

UPDATE CUSTOMERS SET CURDEBT = 0 WHERE CURDEBT IS NULL;
ALTER TABLE CUSTOMERS ALTER CURDEBT SET DEFAULT 0;
ALTER TABLE CUSTOMERS ALTER COLUMN CURDEBT DROP NOT NULL;
--
-- ADD new tables
--

CREATE TABLE LINEREMOVED (
  REMOVEDDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NAME VARCHAR DEFAULT NULL,
  TICKETID VARCHAR DEFAULT NULL,
  PRODUCTID VARCHAR DEFAULT NULL,
  PRODUCTNAME VARCHAR DEFAULT NULL,
  UNITS DOUBLE PRECISION NOT NULL
);


-- UPDATE App' version
UPDATE APPLICATIONS SET NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = $APP_ID{};

-- final script
DELETE FROM SHAREDTICKETS;
