package com.openbravo.pos.payment;

import com.openbravo.pos.forms.AppConfig;
import javax.swing.JPanel;

public class ConfigPaymentPanelEmpty extends javax.swing.JPanel implements PaymentConfiguration {

    /**
     * Creates new form ConfigPaymentPanelGeneric
     */
    public ConfigPaymentPanelEmpty() {
        initComponents();
    }

    @Override
    public JPanel getComponent() {
        return this;
    }

    @Override
    public void loadProperties(AppConfig config) {

    }

    @Override
    public void saveProperties(AppConfig config) {

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(650, 75));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
