package com.openbravo.pos.config;

import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.InputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import com.openbravo.basic.BasicException;
import com.openbravo.pos.forms.AppConfig;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppProperties;
import com.openbravo.pos.forms.JRootFrame;

public class JFrmConfig extends javax.swing.JFrame {

    private final JPanelConfiguration config;

    public JFrmConfig(AppProperties props) {

        initComponents();

        try {
            InputStream is = JRootFrame.class.getResourceAsStream("/images/nycpos-icon-64.png");
            if (is != null) {
                this.setIconImage(ImageIO.read(is));
            }
        } catch (IOException e) {
        }

        setTitle(AppLocal.APP_NAME + " - " + AppLocal.APP_VERSION + " - " +
                 AppLocal.getIntString("Menu.Configuration"));

        addWindowListener(new MyFrameListener());

        config = new JPanelConfiguration(props);

        getContentPane().add(config, BorderLayout.CENTER);

        try {
            config.activate();
        } catch (BasicException e) { // never thrown ;-)
        }
    }

    private class MyFrameListener extends WindowAdapter {

        @Override
        public void windowClosing(WindowEvent evt) {
            if (config.deactivate()) {
                dispose();
            }
        }
        @Override
        public void windowClosed(WindowEvent evt) {
            System.exit(0);
        }
    }
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 450));
        setPreferredSize(new java.awt.Dimension(750, 450));

        setSize(new java.awt.Dimension(758, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                AppConfig config = new AppConfig(args);
                config.load();

// Set the look and feel.
// JG 6 May 2013 to Multicatch
                try {
                    UIManager.setLookAndFeel(config.getProperty("swing.defaultlaf"));
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                             UnsupportedLookAndFeelException e) {
                }

                new JFrmConfig(config).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
